version: '3.7'
services:
  frontend:
    container_name: frontend-hotel
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '' # It should be empty if you want to use local api
    volumes:
      - '.:/app'
    ports:
      - "8080:80"