version: '3.7'
services:
  frontend:
    container_name: frontend-hotel
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '<API_URL>' # here should be api url without /api
    volumes:
      - '.:/app'
    ports:
      - "8080:80"